// src/data/products.js

const allProducts = [
  {
    id: 'prod1',
    name: 'Nike ACG "Cinder Cone"',
    description: 'Veste coupe-vent pour Homme',
    imageSrc: '/images/psg-nike-home-mini-kit-2024-25-infants-with-barcola-29-printing_ss5_p-201613711+pv-2+u-udkqgpmseogwdvebws71+v-erbn1f4cmmrvjywtgwd6.jpg', // Chemin de l'image
    price: 179.99,
    category: 'Vestes et Sweats',
    gender: 'Homme',
    sport: 'Randonnée',
    brand: 'Nike',
    style: 'Oversize',
    isNew: true,
  },
  {
    id: 'prod2',
    name: 'Nike Air Rift',
    description: 'Chaussure pour femme',
    imageSrc: '/images/street-nike.webp', // Chemin de l'image
    price: 129.99,
    category: 'Chaussures',
    gender: 'Femme',
    sport: 'Running',
    brand: 'Nike',
    style: 'Standard',
    isNew: true,
  },
  {
    id: 'prod3',
    name: 'Nike 24.7 PerfectStretch',
    description: 'Pantalon ample à taille haute et jambes larges Dri-FIT pour femme',
    imageSrc: '/images/Raphinha.webp',
    price: 89.99,
    category: 'Pantalons et leggings',
    gender: 'Femme',
    sport: 'Training',
    brand: 'Nike',
    style: 'Ample',
    isNew: true,
  },
  {
    id: 'prod4',
    name: 'Adidas Ultraboost 24',
    description: 'Chaussure de running pour homme',
    imageSrc: '/images/adidas-ultraboost.webp', // Chemin de l'image
    price: 180.00,
    category: 'Chaussures',
    gender: 'Homme',
    sport: 'Running',
    brand: 'Adidas',
    style: 'Standard',
    isNew: true,
  },
  {
    id: 'prod5',
    name: 'Adidas Tiro 23',
    description: 'Pantalon d\'entraînement unisexe',
    imageSrc: '/images/adidas-tiro.webp', // Chemin de l'image
    price: 55.00,
    category: 'Pantalons et leggings',
    gender: 'Mixte',
    sport: 'Football',
    brand: 'Adidas',
    style: 'Standard',
    isNew: true,
  },
  {
    id: 'prod6',
    name: 'Nike Tech Fleece Hoodie',
    description: 'Sweat à capuche pour homme',
    imageSrc: '/images/nike-tech-fleece.webp', // Chemin de l'image
    price: 100.00,
    category: 'Sweats à capuche et sweats',
    gender: 'Homme',
    sport: 'Lifestyle',
    brand: 'Nike',
    style: 'Oversize',
    isNew: true,
  },
  {
    id: 'prod7',
    name: 'Puma Cali Dream',
    description: 'Sneakers pour femme',
    imageSrc: '/images/puma-cali-dream.webp', // Chemin de l'image
    price: 85.00,
    category: 'Chaussures',
    gender: 'Femme',
    sport: 'Lifestyle',
    brand: 'Puma',
    style: 'Standard',
    isNew: true,
  },
  {
    id: 'prod8',
    name: 'Reebok Nano X4',
    description: 'Chaussures de cross-training',
    imageSrc: '/images/reebok-nano.webp', // Chemin de l'image
    price: 140.00,
    category: 'Chaussures',
    gender: 'Mixte',
    sport: 'Training',
    brand: 'Reebok',
    style: 'Standard',
    isNew: true,
  },
  {
    id: 'prod9',
    name: 'Nike Dri-FIT T-shirt',
    description: 'T-shirt de sport pour enfant',
    imageSrc: '/images/nike-dri-fit-tee.webp', // Chemin de l'image
    price: 25.00,
    category: 'Hauts et t-shirts',
    gender: 'Enfant - Garçon',
    sport: 'Basketball',
    brand: 'Nike',
    style: 'Standard',
    isNew: true,
  },
  {
    id: 'prod10',
    name: 'Adidas Kids Shorts',
    description: 'Shorts de sport pour fille',
    imageSrc: '/images/adidas-kids-shorts.webp', // Chemin de l'image
    price: 20.00,
    category: 'Shorts',
    gender: 'Enfant - Fille',
    sport: 'Running',
    brand: 'Adidas',
    style: 'Standard',
    isNew: true,
  },
  {
    id: 'prod11',
    name: 'Chaussure de football Nike Phantom GX Elite FG',
    description: 'Chaussures crampons mixtes',
    imageSrc: '/images/nike-phantom-gx-elite.webp',
    price: 250.00,
    category: 'Chaussures',
    gender: 'Mixte',
    sport: 'Football',
    brand: 'Nike',
    style: 'Standard',
    isNew: true,
  },
  {
    id: 'prod12',
    name: 'Ensemble survêtement Adidas Sereno',
    description: 'Survêtement homme en polyester',
    imageSrc: '/images/adidas-sereno-tracksuit.webp',
    price: 75.00,
    category: 'Survêtements',
    gender: 'Homme',
    sport: 'Football',
    brand: 'Adidas',
    style: 'Standard',
    isNew: true,
  },
  {
    id: 'prod13',
    name: 'Chaussettes Nike Everyday Plus Cushioned',
    description: 'Lot de 3 paires de chaussettes unisexes',
    imageSrc: '/images/nike-socks.webp',
    price: 18.00,
    category: 'Chaussettes',
    gender: 'Mixte',
    sport: 'Lifestyle',
    brand: 'Nike',
    style: 'Standard',
    isNew: true,
  },
  {
    id: 'prod14',
    name: 'Sac à dos Nike Brasilia',
    description: 'Sac à dos pour le sport et le quotidien',
    imageSrc: '/images/nike-brasilia-backpack.webp',
    price: 45.00,
    category: 'Accessoires et équipement',
    gender: 'Mixte',
    sport: 'Training',
    brand: 'Nike',
    style: 'Standard',
    isNew: true,
  },
  {
    id: 'prod15',
    name: 'Gants de gardien Adidas Predator Match',
    description: 'Gants de football pour homme',
    imageSrc: '/images/adidas-predator-gloves.webp',
    price: 35.00,
    category: 'Accessoires et équipement',
    gender: 'Homme',
    sport: 'Football',
    brand: 'Adidas',
    style: 'Standard',
    isNew: true,
  },
];

export default allProducts;